import React, { FC, PropsWithChildren } from "react";
import Head from 'next/head';
import MainHeader from "@/components/Main/MainHeader";
import MainFooter from "@/components/Main/MainFooter";

const MainLayout: FC<PropsWithChildren<{}>> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainHeader />

            <main>
                { children }
            </main>

            <MainFooter />
        </>
    )
}

export default MainLayout;